use shakesdb1

-- CREATE TABLE AND INSERT DATA
CREATE TABLE EMPLOYEE (EMPLOYEE_ID INT, NAME VARCHAR(255), SALARY DECIMAL(10,2))

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000)
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(103,'Den',11000)

SELECT  * FROM EMPLOYEE
ORDER BY EMPLOYEE_ID DESC

UPDATE EMPLOYEE
SET SALARY = '12000'
WHERE  EMPLOYEE_ID LIKE '103'

DELETE FROM EMPLOYEE
WHERE EMPLOYEE_ID LIKE '103'

--GROUP BY
SELECT EMPLOYEE_ID, NAME, SALARY FROM EMPLOYEE
GROUP BY EMPLOYEE_ID, NAME, SALARY

-- PROVIDE CONSECUTIVE ROW IN TABLE (IT BRINGS OUT THE NUMBER OF ROW OF EACH NAME)
SELECT EMPLOYEE_ID, NAME, SALARY, ROW_NUMBER () OVER(PARTITION BY EMPLOYEE_ID,NAME,SALARY ORDER BY EMPLOYEE_ID) 
AS ROW_NUMBER FROM EMPLOYEE

-- FIND THE EMPLOYEE WITH THE 2ND HIGHEST/MAX SALARY
SELECT MAX(SALARY) AS SALARY FROM EMPLOYEE WHERE SALARY NOT IN 
(SELECT MAX(SALARY) AS SALARY FROM EMPLOYEE)

--THE WITH CLAUSE DISPLAYS THE NAME AND EMPLOYEEID OF THE 2ND HIGHEST/MAX SALARY
WITH 
TEMP AS( SELECT MAX(SALARY) AS SALARY FROM EMPLOYEE WHERE SALARY NOT IN 
(SELECT MAX(SALARY) AS SALARY FROM EMPLOYEE))
SELECT a.* FROM EMPLOYEE a JOIN TEMP b ON a.SALARY = b.SALARY








