use [AdventureWorksDW2012]

--
SELECT * FROM [dbo].[DimCustomer]

--SHOW ME ALL THE DEPARTMENT NAMES
SELECT FirstName FROM [dbo].[DimCustomer]

--SHOW ME ALL THE BIRTHDATE
SELECT BirthDate FROM [dbo].[DimCustomer]

-- SHOW ME ALL THE DISTINCT BIRTHDATE
SELECT DISTINCT FirstName FROM [dbo].[DimCustomer]
SELECT DISTINCT Gender FROM [dbo].[DimCustomer]

-- SHOW ME ALL THE CUSTOMERS FIRSTNAME WITH A SPECIFIC BIRTHDATE
SELECT FirstName, BirthDate FROM [dbo].[DimCustomer]
WHERE BirthDate LIKE '1954-03-15'

--GIVE ME ALL THE EMPLOYEES FROM THE EMPLOYEE TABLE
SELECT * FROM [dbo].[DimEmployee]

-- GIVE ME ALL THE EMPLOYEES WHO HAVE A PAY FREQUENCY =2
SELECT * FROM [dbo].[DimEmployee] WHERE PayFrequency=2

-- GIVE ME A LIST OF ALL EMPLOYEES WHO HAVE VACATION HOURS = 2 OR 3
SELECT * FROM [dbo].[DimEmployee] WHERE VacationHours IN (2,26)

--GIVE ME A LIST OF EMPLOYEE WHO HAVE A TITLE AS NETWORK ADMINISTRATOR
SELECT * FROM [dbo].[DimEmployee] WHERE Title LIKE 'Network Administrator'

--GIVE ME ALL THE EMPLOYEE WHO HAVE THE WORD MANAGER IN THEIR TITLE
SELECT * FROM [dbo].[DimEmployee] WHERE Title LIKE '%Control%'

-- GIVE ME ALL EMPLOYEES BORN AFTER JAN 1, 1980
SELECT * FROM [dbo].[DimEmployee] WHERE BirthDate >'1/1/1985'

--GIVE ME ALL EMPLOYEES WHO ARE BORN BETWEEN JAN 1, 1970  AND JAN 1, 1980
SELECT * FROM [dbo].[DimEmployee] WHERE BirthDate > '1/1/1970' AND BirthDate <'1/1/1980'

SELECT * FROM [dbo].[DimEmployee] WHERE BirthDate BETWEEN '1/1/1970' AND '1/1/1980'




